#pragma once

#include <stdint.h>

#define POOL_BG 0x0841
#define POOL_C 0x07ff
#define POOL_W 0xffff
#define POOL_STICK 0xA145

#define POOL7(c) c, c, c, c, c, c, c
#define POOL_BIG_ROW0 POOL7(POOL_BG), POOL7(POOL_BG), POOL7(POOL_BG), POOL7(POOL_BG), POOL7(POOL_BG), POOL7(POOL_BG), POOL7(POOL_STICK), POOL7(POOL_BG)
#define POOL_BIG_ROW1 POOL7(POOL_BG), POOL7(POOL_BG), POOL7(POOL_BG), POOL7(POOL_BG), POOL7(POOL_BG), POOL7(POOL_STICK), POOL7(POOL_STICK), POOL7(POOL_BG)
#define POOL_BIG_ROW2 POOL7(POOL_BG), POOL7(POOL_BG), POOL7(POOL_BG), POOL7(POOL_C), POOL7(POOL_C), POOL7(POOL_C), POOL7(POOL_STICK), POOL7(POOL_BG)
#define POOL_BIG_ROW3 POOL7(POOL_BG), POOL7(POOL_BG), POOL7(POOL_C), POOL7(POOL_W), POOL7(POOL_W), POOL7(POOL_C), POOL7(POOL_BG), POOL7(POOL_BG)
#define POOL_BIG_ROW4 POOL7(POOL_BG), POOL7(POOL_C), POOL7(POOL_W), POOL7(POOL_W), POOL7(POOL_W), POOL7(POOL_C), POOL7(POOL_BG), POOL7(POOL_BG)
#define POOL_BIG_ROW5 POOL7(POOL_BG), POOL7(POOL_C), POOL7(POOL_W), POOL7(POOL_W), POOL7(POOL_W), POOL7(POOL_C), POOL7(POOL_BG), POOL7(POOL_BG)
#define POOL_BIG_ROW6 POOL7(POOL_BG), POOL7(POOL_BG), POOL7(POOL_C), POOL7(POOL_C), POOL7(POOL_C), POOL7(POOL_C), POOL7(POOL_BG), POOL7(POOL_BG)
#define POOL_BIG_ROW7 POOL7(POOL_BG), POOL7(POOL_BG), POOL7(POOL_BG), POOL7(POOL_BG), POOL7(POOL_BG), POOL7(POOL_BG), POOL7(POOL_BG), POOL7(POOL_BG)

static const uint16_t image_data_pool_big[56 * 56] = {
    POOL_BIG_ROW0, POOL_BIG_ROW0, POOL_BIG_ROW0, POOL_BIG_ROW0, POOL_BIG_ROW0, POOL_BIG_ROW0, POOL_BIG_ROW0,
    POOL_BIG_ROW1, POOL_BIG_ROW1, POOL_BIG_ROW1, POOL_BIG_ROW1, POOL_BIG_ROW1, POOL_BIG_ROW1, POOL_BIG_ROW1,
    POOL_BIG_ROW2, POOL_BIG_ROW2, POOL_BIG_ROW2, POOL_BIG_ROW2, POOL_BIG_ROW2, POOL_BIG_ROW2, POOL_BIG_ROW2,
    POOL_BIG_ROW3, POOL_BIG_ROW3, POOL_BIG_ROW3, POOL_BIG_ROW3, POOL_BIG_ROW3, POOL_BIG_ROW3, POOL_BIG_ROW3,
    POOL_BIG_ROW4, POOL_BIG_ROW4, POOL_BIG_ROW4, POOL_BIG_ROW4, POOL_BIG_ROW4, POOL_BIG_ROW4, POOL_BIG_ROW4,
    POOL_BIG_ROW5, POOL_BIG_ROW5, POOL_BIG_ROW5, POOL_BIG_ROW5, POOL_BIG_ROW5, POOL_BIG_ROW5, POOL_BIG_ROW5,
    POOL_BIG_ROW6, POOL_BIG_ROW6, POOL_BIG_ROW6, POOL_BIG_ROW6, POOL_BIG_ROW6, POOL_BIG_ROW6, POOL_BIG_ROW6,
    POOL_BIG_ROW7, POOL_BIG_ROW7, POOL_BIG_ROW7, POOL_BIG_ROW7, POOL_BIG_ROW7, POOL_BIG_ROW7, POOL_BIG_ROW7,
};

#undef POOL_BIG_ROW0
#undef POOL_BIG_ROW1
#undef POOL_BIG_ROW2
#undef POOL_BIG_ROW3
#undef POOL_BIG_ROW4
#undef POOL_BIG_ROW5
#undef POOL_BIG_ROW6
#undef POOL_BIG_ROW7
#undef POOL7
#undef POOL_STICK
#undef POOL_W
#undef POOL_C
#undef POOL_BG
