#pragma once

#include <stdint.h>

#define POOL_BG 0x0841
#define POOL_C 0x07ff
#define POOL_W 0xffff
#define POOL_STICK 0xA145

#define POOL4(c) c, c, c, c
#define POOL_SMALL_ROW0 POOL4(POOL_BG), POOL4(POOL_BG), POOL4(POOL_BG), POOL4(POOL_BG), POOL4(POOL_BG), POOL4(POOL_BG), POOL4(POOL_STICK), POOL4(POOL_BG), POOL4(POOL_BG), POOL4(POOL_BG)
#define POOL_SMALL_ROW1 POOL4(POOL_BG), POOL4(POOL_BG), POOL4(POOL_BG), POOL4(POOL_BG), POOL4(POOL_BG), POOL4(POOL_STICK), POOL4(POOL_STICK), POOL4(POOL_BG), POOL4(POOL_BG), POOL4(POOL_BG)
#define POOL_SMALL_ROW2 POOL4(POOL_BG), POOL4(POOL_BG), POOL4(POOL_BG), POOL4(POOL_C), POOL4(POOL_C), POOL4(POOL_C), POOL4(POOL_STICK), POOL4(POOL_BG), POOL4(POOL_BG), POOL4(POOL_BG)
#define POOL_SMALL_ROW3 POOL4(POOL_BG), POOL4(POOL_BG), POOL4(POOL_C), POOL4(POOL_W), POOL4(POOL_W), POOL4(POOL_C), POOL4(POOL_BG), POOL4(POOL_BG), POOL4(POOL_BG), POOL4(POOL_BG)
#define POOL_SMALL_ROW4 POOL4(POOL_BG), POOL4(POOL_C), POOL4(POOL_W), POOL4(POOL_W), POOL4(POOL_W), POOL4(POOL_C), POOL4(POOL_BG), POOL4(POOL_BG), POOL4(POOL_BG), POOL4(POOL_BG)
#define POOL_SMALL_ROW5 POOL4(POOL_BG), POOL4(POOL_C), POOL4(POOL_W), POOL4(POOL_W), POOL4(POOL_W), POOL4(POOL_C), POOL4(POOL_BG), POOL4(POOL_BG), POOL4(POOL_BG), POOL4(POOL_BG)
#define POOL_SMALL_ROW6 POOL4(POOL_BG), POOL4(POOL_BG), POOL4(POOL_C), POOL4(POOL_C), POOL4(POOL_C), POOL4(POOL_C), POOL4(POOL_BG), POOL4(POOL_BG), POOL4(POOL_BG), POOL4(POOL_BG)
#define POOL_SMALL_ROW7 POOL4(POOL_BG), POOL4(POOL_BG), POOL4(POOL_BG), POOL4(POOL_BG), POOL4(POOL_BG), POOL4(POOL_BG), POOL4(POOL_BG), POOL4(POOL_BG), POOL4(POOL_BG), POOL4(POOL_BG)
#define POOL_SMALL_ROW8 POOL_SMALL_ROW7
#define POOL_SMALL_ROW9 POOL_SMALL_ROW7

static const uint16_t image_data_pool_small[40 * 40] = {
    POOL_SMALL_ROW0, POOL_SMALL_ROW0, POOL_SMALL_ROW0, POOL_SMALL_ROW0,
    POOL_SMALL_ROW1, POOL_SMALL_ROW1, POOL_SMALL_ROW1, POOL_SMALL_ROW1,
    POOL_SMALL_ROW2, POOL_SMALL_ROW2, POOL_SMALL_ROW2, POOL_SMALL_ROW2,
    POOL_SMALL_ROW3, POOL_SMALL_ROW3, POOL_SMALL_ROW3, POOL_SMALL_ROW3,
    POOL_SMALL_ROW4, POOL_SMALL_ROW4, POOL_SMALL_ROW4, POOL_SMALL_ROW4,
    POOL_SMALL_ROW5, POOL_SMALL_ROW5, POOL_SMALL_ROW5, POOL_SMALL_ROW5,
    POOL_SMALL_ROW6, POOL_SMALL_ROW6, POOL_SMALL_ROW6, POOL_SMALL_ROW6,
    POOL_SMALL_ROW7, POOL_SMALL_ROW7, POOL_SMALL_ROW7, POOL_SMALL_ROW7,
    POOL_SMALL_ROW8, POOL_SMALL_ROW8, POOL_SMALL_ROW8, POOL_SMALL_ROW8,
    POOL_SMALL_ROW9, POOL_SMALL_ROW9, POOL_SMALL_ROW9, POOL_SMALL_ROW9,
};

#undef POOL_SMALL_ROW0
#undef POOL_SMALL_ROW1
#undef POOL_SMALL_ROW2
#undef POOL_SMALL_ROW3
#undef POOL_SMALL_ROW4
#undef POOL_SMALL_ROW5
#undef POOL_SMALL_ROW6
#undef POOL_SMALL_ROW7
#undef POOL_SMALL_ROW8
#undef POOL_SMALL_ROW9
#undef POOL4
#undef POOL_STICK
#undef POOL_W
#undef POOL_C
#undef POOL_BG
