#pragma once

#include <stdint.h>

#define GS_BG 0x0841
#define GS_C 0x07ff
#define GS_W 0xffff
#define GS_G 0x07e0
#define GS_Y 0xffe0

#define GS7(c) c, c, c, c, c, c, c
#define GS_BIG_ROW0 GS7(GS_BG), GS7(GS_BG), GS7(GS_BG), GS7(GS_BG), GS7(GS_BG), GS7(GS_BG), GS7(GS_BG), GS7(GS_BG)
#define GS_BIG_ROW1 GS7(GS_BG), GS7(GS_BG), GS7(GS_C), GS7(GS_C), GS7(GS_BG), GS7(GS_BG), GS7(GS_BG), GS7(GS_BG)
#define GS_BIG_ROW2 GS7(GS_BG), GS7(GS_C), GS7(GS_C), GS7(GS_C), GS7(GS_C), GS7(GS_BG), GS7(GS_BG), GS7(GS_BG)
#define GS_BIG_ROW3 GS7(GS_C), GS7(GS_C), GS7(GS_W), GS7(GS_W), GS7(GS_C), GS7(GS_C), GS7(GS_BG), GS7(GS_BG)
#define GS_BIG_ROW4 GS7(GS_C), GS7(GS_W), GS7(GS_W), GS7(GS_W), GS7(GS_W), GS7(GS_C), GS7(GS_BG), GS7(GS_BG)
#define GS_BIG_ROW5 GS7(GS_C), GS7(GS_W), GS7(GS_W), GS7(GS_G), GS7(GS_W), GS7(GS_C), GS7(GS_BG), GS7(GS_BG)
#define GS_BIG_ROW6 GS7(GS_C), GS7(GS_W), GS7(GS_G), GS7(GS_G), GS7(GS_W), GS7(GS_C), GS7(GS_BG), GS7(GS_BG)
#define GS_BIG_ROW7 GS7(GS_C), GS7(GS_C), GS7(GS_W), GS7(GS_W), GS7(GS_C), GS7(GS_C), GS7(GS_Y), GS7(GS_BG)

static const uint16_t image_data_gravity_slice_big[56 * 56] = {
    GS_BIG_ROW0, GS_BIG_ROW0, GS_BIG_ROW0, GS_BIG_ROW0, GS_BIG_ROW0, GS_BIG_ROW0, GS_BIG_ROW0,
    GS_BIG_ROW1, GS_BIG_ROW1, GS_BIG_ROW1, GS_BIG_ROW1, GS_BIG_ROW1, GS_BIG_ROW1, GS_BIG_ROW1,
    GS_BIG_ROW2, GS_BIG_ROW2, GS_BIG_ROW2, GS_BIG_ROW2, GS_BIG_ROW2, GS_BIG_ROW2, GS_BIG_ROW2,
    GS_BIG_ROW3, GS_BIG_ROW3, GS_BIG_ROW3, GS_BIG_ROW3, GS_BIG_ROW3, GS_BIG_ROW3, GS_BIG_ROW3,
    GS_BIG_ROW4, GS_BIG_ROW4, GS_BIG_ROW4, GS_BIG_ROW4, GS_BIG_ROW4, GS_BIG_ROW4, GS_BIG_ROW4,
    GS_BIG_ROW5, GS_BIG_ROW5, GS_BIG_ROW5, GS_BIG_ROW5, GS_BIG_ROW5, GS_BIG_ROW5, GS_BIG_ROW5,
    GS_BIG_ROW6, GS_BIG_ROW6, GS_BIG_ROW6, GS_BIG_ROW6, GS_BIG_ROW6, GS_BIG_ROW6, GS_BIG_ROW6,
    GS_BIG_ROW7, GS_BIG_ROW7, GS_BIG_ROW7, GS_BIG_ROW7, GS_BIG_ROW7, GS_BIG_ROW7, GS_BIG_ROW7,
};

#undef GS_BIG_ROW0
#undef GS_BIG_ROW1
#undef GS_BIG_ROW2
#undef GS_BIG_ROW3
#undef GS_BIG_ROW4
#undef GS_BIG_ROW5
#undef GS_BIG_ROW6
#undef GS_BIG_ROW7
#undef GS7
#undef GS_Y
#undef GS_G
#undef GS_W
#undef GS_C
#undef GS_BG
