#pragma once

#include <stdint.h>

#define GS_BG 0x0841
#define GS_C 0x07ff
#define GS_W 0xffff
#define GS_G 0x07e0

#define GS4(c) c, c, c, c
#define GS_SMALL_ROW0 GS4(GS_BG), GS4(GS_BG), GS4(GS_BG), GS4(GS_BG), GS4(GS_BG), GS4(GS_BG), GS4(GS_BG), GS4(GS_BG), GS4(GS_BG), GS4(GS_BG)
#define GS_SMALL_ROW1 GS4(GS_BG), GS4(GS_BG), GS4(GS_BG), GS4(GS_C), GS4(GS_C), GS4(GS_BG), GS4(GS_BG), GS4(GS_BG), GS4(GS_BG), GS4(GS_BG)
#define GS_SMALL_ROW2 GS4(GS_BG), GS4(GS_BG), GS4(GS_C), GS4(GS_C), GS4(GS_C), GS4(GS_C), GS4(GS_BG), GS4(GS_BG), GS4(GS_BG), GS4(GS_BG)
#define GS_SMALL_ROW3 GS4(GS_BG), GS4(GS_C), GS4(GS_C), GS4(GS_W), GS4(GS_W), GS4(GS_C), GS4(GS_C), GS4(GS_BG), GS4(GS_BG), GS4(GS_BG)
#define GS_SMALL_ROW4 GS4(GS_BG), GS4(GS_C), GS4(GS_W), GS4(GS_W), GS4(GS_W), GS4(GS_W), GS4(GS_C), GS4(GS_BG), GS4(GS_BG), GS4(GS_BG)
#define GS_SMALL_ROW5 GS4(GS_BG), GS4(GS_C), GS4(GS_W), GS4(GS_W), GS4(GS_G), GS4(GS_W), GS4(GS_C), GS4(GS_BG), GS4(GS_BG), GS4(GS_BG)
#define GS_SMALL_ROW6 GS4(GS_BG), GS4(GS_C), GS4(GS_W), GS4(GS_G), GS4(GS_G), GS4(GS_W), GS4(GS_C), GS4(GS_BG), GS4(GS_BG), GS4(GS_BG)
#define GS_SMALL_ROW7 GS4(GS_BG), GS4(GS_C), GS4(GS_C), GS4(GS_W), GS4(GS_W), GS4(GS_C), GS4(GS_C), GS4(GS_BG), GS4(GS_BG), GS4(GS_BG)
#define GS_SMALL_ROW8 GS4(GS_BG), GS4(GS_BG), GS4(GS_C), GS4(GS_C), GS4(GS_C), GS4(GS_C), GS4(GS_BG), GS4(GS_BG), GS4(GS_BG), GS4(GS_BG)
#define GS_SMALL_ROW9 GS4(GS_BG), GS4(GS_BG), GS4(GS_BG), GS4(GS_C), GS4(GS_C), GS4(GS_BG), GS4(GS_BG), GS4(GS_BG), GS4(GS_BG), GS4(GS_BG)

static const uint16_t image_data_gravity_slice_small[40 * 40] = {
    GS_SMALL_ROW0, GS_SMALL_ROW0, GS_SMALL_ROW0, GS_SMALL_ROW0,
    GS_SMALL_ROW1, GS_SMALL_ROW1, GS_SMALL_ROW1, GS_SMALL_ROW1,
    GS_SMALL_ROW2, GS_SMALL_ROW2, GS_SMALL_ROW2, GS_SMALL_ROW2,
    GS_SMALL_ROW3, GS_SMALL_ROW3, GS_SMALL_ROW3, GS_SMALL_ROW3,
    GS_SMALL_ROW4, GS_SMALL_ROW4, GS_SMALL_ROW4, GS_SMALL_ROW4,
    GS_SMALL_ROW5, GS_SMALL_ROW5, GS_SMALL_ROW5, GS_SMALL_ROW5,
    GS_SMALL_ROW6, GS_SMALL_ROW6, GS_SMALL_ROW6, GS_SMALL_ROW6,
    GS_SMALL_ROW7, GS_SMALL_ROW7, GS_SMALL_ROW7, GS_SMALL_ROW7,
    GS_SMALL_ROW8, GS_SMALL_ROW8, GS_SMALL_ROW8, GS_SMALL_ROW8,
    GS_SMALL_ROW9, GS_SMALL_ROW9, GS_SMALL_ROW9, GS_SMALL_ROW9,
};

#undef GS_SMALL_ROW0
#undef GS_SMALL_ROW1
#undef GS_SMALL_ROW2
#undef GS_SMALL_ROW3
#undef GS_SMALL_ROW4
#undef GS_SMALL_ROW5
#undef GS_SMALL_ROW6
#undef GS_SMALL_ROW7
#undef GS_SMALL_ROW8
#undef GS_SMALL_ROW9
#undef GS4
#undef GS_G
#undef GS_W
#undef GS_C
#undef GS_BG
